// Session squash — compress recent interactions into a summary.
//
// squashRecent(db, sessionId, count, config) → Promise<SessionData>
// squashInteractive(db, sessionId, options) → Promise<SquashArchiveEntry>
// squashPreview(db, sessionId, range) → Promise<SquashPreview>
// squashRollback(db, sessionId, archiveId) → Promise<SquashRollbackResult>
// getSquashLog(db, sessionId) → Promise<SquashArchiveEntry[]>
// getSquashStats(db, sessionId) → Promise<SquashStats>
//
// Takes interaction pairs from the session, generates a summary via an
// injected summarizer function, replaces the original messages with a single
// summary message, and archives the originals in the squash_archives table.
//
// Conventions: data + functions, no class.

import { asc, eq } from "drizzle-orm";
import type { DB } from "../db/client";
import { messages, sessions, squashArchives } from "../db/schema";
import type { MessageData, SessionData } from "./types";

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

/**
 * A contiguous range of message indices to squash.
 * Indices are 0-based into the session's chronological message list.
 */
export type SquashRange = {
  /** Start index (inclusive). */
  startIndex: number;
  /** End index (inclusive). */
  endIndex: number;
};

/**
 * Configuration for squash behavior.
 */
export type SquashConfig = {
  /** Minimum number of messages required before a squash is performed. */
  minMessages: number;
  /** Model to use for summarization (passed to the summarizer). */
  summaryModel?: string;
  /** Hot file paths to preserve as snapshots in the squash metadata. */
  hotFiles?: string[];
};

/**
 * Options for an interactive (user-specified-range) squash.
 */
export type InteractiveSquashOptions = {
  /** The exact range of messages to squash. */
  range: SquashRange;
  /** Squash configuration overrides. */
  config?: SquashConfig;
  /** Injected summarizer (defaults to a local digest). */
  summarizer?: SquashSummarizer;
};

/**
 * Preview of a squash operation — shows what would happen without
 * actually modifying the database.
 */
export type SquashPreview = {
  /** The range of message indices that would be squashed. */
  range: SquashRange;
  /** Total number of messages in the range. */
  messageCount: number;
  /** Estimated token savings (rough: content length / 4). */
  estimatedTokensSaved: number;
  /** Preview summary text (generated by the summarizer). */
  previewSummary: string;
  /** The messages that would be squashed (for UI display). */
  messages: MessageData[];
};

/**
 * Result of a rollback operation.
 */
export type SquashRollbackResult = {
  /** The number of messages restored. */
  restoredCount: number;
  /** The ID of the summary message that was removed. */
  summaryMessageId: string | null;
  /** Whether the rollback was applied. */
  applied: boolean;
};

/**
 * A single squash archive entry stored in the squash_archives table.
 */
export type SquashArchiveEntry = {
  /** Unique archive ID. */
  id: string;
  /** Session ID. */
  sessionId: string;
  /** ID of the summary message that replaced the squashed messages. */
  summaryMessageId: string | null;
  /** Summary text generated during squash. */
  summary: string;
  /** Number of messages that were squashed. */
  messageCount: number;
  /** IDs of the original messages. */
  messageIds: string[];
  /** Estimated token savings. */
  estimatedTokensSaved: number;
  /** Hot files snapshotted during the squash. */
  hotFiles: string[];
  /** Whether a rollback has been applied. */
  rollbackApplied: boolean;
  /** When the rollback was applied, if any. */
  rollbackTimestamp: Date | null;
  /** When the squash was performed. */
  createdAt: Date;
};

/**
 * Aggregated squash statistics for a session.
 */
export type SquashStats = {
  /** Total number of squash operations performed. */
  totalSquashes: number;
  /** Total number of messages squashed across all operations. */
  totalMessagesSquashed: number;
  /** Total estimated token savings across all operations. */
  totalTokensSaved: number;
  /** Number of squashes that have been rolled back. */
  rollbacksPerformed: number;
  /** Timestamp of the most recent squash. */
  lastSquashTimestamp: Date | null;
  /** Average messages per squash. */
  averageMessagesPerSquash: number;
};

/**
 * A summary function: receives the raw messages to summarize and the config,
 * returns a plain-text summary string. This is injected so the squash
 * operation stays decoupled from the LLM layer.
 */
export type SquashSummarizer = (
  messages: MessageData[],
  config: SquashConfig,
) => Promise<string>;

/**
 * The default squash config — conservative defaults that match the
 * spec's compaction threshold semantics.
 */
export const DEFAULT_SQUASH_CONFIG: SquashConfig = {
  minMessages: 10,
};

// ---------------------------------------------------------------------------
// squashRecent — public entry point (existing interface, enhanced)
// ---------------------------------------------------------------------------

/**
 * Compress the most recent `count` interaction pairs into a single summary
 * message and archive the originals.
 *
 * An "interaction pair" is a contiguous user message followed by an assistant
 * message (possibly with interleaved tool messages). The function walks
 * backwards from the end of the message list, collects `count` such pairs,
 * replaces them with one summary message, and writes the original content
 * into the session's squash_archives table.
 *
 * @param db         Database handle
 * @param sessionId  Target session
 * @param count      Number of recent interaction pairs to squash
 * @param config     Squash configuration
 * @param summarizer Injected summarizer (defaults to a local digest)
 * @returns The updated session entry
 */
export async function squashRecent(
  db: DB,
  sessionId: string,
  count: number,
  config: SquashConfig = DEFAULT_SQUASH_CONFIG,
  summarizer?: SquashSummarizer,
): Promise<SessionData> {
  // 1. Fetch all messages for this session, ordered by creation time.
  const allMessages = (await db.db
    .select()
    .from(messages)
    .where(eq(messages.sessionId, sessionId))
    .orderBy(asc(messages.createdAt))) as unknown as MessageData[];

  if (allMessages.length < config.minMessages) {
    const [session] = await db.db
      .select()
      .from(sessions)
      .where(eq(sessions.id, sessionId))
      .limit(1);
    return session as unknown as SessionData;
  }

  // 2. Identify the boundary: walk backwards, collect `count` interaction pairs.
  const pairs = collectRecentPairs(allMessages, count);

  if (pairs.length === 0) {
    const [session] = await db.db
      .select()
      .from(sessions)
      .where(eq(sessions.id, sessionId))
      .limit(1);
    return session as unknown as SessionData;
  }

  const firstPairStart = pairs[0][0];
  const lastPairEnd = pairs[pairs.length - 1][1];
  const squashedMessages = allMessages.slice(firstPairStart, lastPairEnd + 1);

  // 3. Generate summary text.
  const summarizeFn = summarizer ?? defaultSquashSummarizer;
  const summaryText = await summarizeFn(squashedMessages, config);

  // 4. Perform the squash and archive.
  const { archive, updatedSession } = await executeSquash(
    db,
    sessionId,
    squashedMessages,
    summaryText,
    config,
  );

  return updatedSession;
}

// ---------------------------------------------------------------------------
// squashInteractive — user-specified range squash
// ---------------------------------------------------------------------------

/**
 * Squash a user-specified range of messages into a single summary.
 *
 * Unlike `squashRecent`, the caller explicitly provides the message index
 * range (start to end, inclusive). This enables the UI to let users select
 * exactly which messages to compress.
 *
 * @param db        Database handle
 * @param sessionId Target session
 * @param options   Range, config, and summarizer
 * @returns The archive entry for the newly created squash
 */
export async function squashInteractive(
  db: DB,
  sessionId: string,
  options: InteractiveSquashOptions,
): Promise<SquashArchiveEntry> {
  const { range, config, summarizer } = options;
  const resolvedConfig = config ?? DEFAULT_SQUASH_CONFIG;

  // 1. Fetch all messages.
  const allMessages = (await db.db
    .select()
    .from(messages)
    .where(eq(messages.sessionId, sessionId))
    .orderBy(asc(messages.createdAt))) as unknown as MessageData[];

  // Validate range bounds.
  if (range.startIndex < 0 || range.endIndex >= allMessages.length || range.startIndex > range.endIndex) {
    throw new Error(
      `Invalid squash range [${range.startIndex}, ${range.endIndex}] — session has ${allMessages.length} messages`,
    );
  }

  const squashedMessages = allMessages.slice(range.startIndex, range.endIndex + 1);

  if (squashedMessages.length < resolvedConfig.minMessages) {
    throw new Error(
      `Range has ${squashedMessages.length} messages, minimum is ${resolvedConfig.minMessages}`,
    );
  }

  // 2. Generate summary.
  const summarizeFn = summarizer ?? defaultSquashSummarizer;
  const summaryText = await summarizeFn(squashedMessages, resolvedConfig);

  // 3. Execute the squash and return the archive entry.
  const { archive } = await executeSquash(
    db,
    sessionId,
    squashedMessages,
    summaryText,
    resolvedConfig,
  );

  return archive;
}

// ---------------------------------------------------------------------------
// squashPreview — preview a squash without making changes
// ---------------------------------------------------------------------------

/**
 * Preview what a squash would do without modifying the database.
 *
 * Generates the summary text and returns metadata about the operation,
 * allowing the UI to show the user what will happen before they commit.
 *
 * @param db        Database handle
 * @param sessionId Target session
 * @param range     The range of messages to preview
 * @param summarizer Optional summarizer
 * @returns A preview object with summary and metadata
 */
export async function squashPreview(
  db: DB,
  sessionId: string,
  range: SquashRange,
  summarizer?: SquashSummarizer,
): Promise<SquashPreview> {
  const config = DEFAULT_SQUASH_CONFIG;

  // 1. Fetch messages.
  const allMessages = (await db.db
    .select()
    .from(messages)
    .where(eq(messages.sessionId, sessionId))
    .orderBy(asc(messages.createdAt))) as unknown as MessageData[];

  // Validate range bounds.
  if (range.startIndex < 0 || range.endIndex >= allMessages.length || range.startIndex > range.endIndex) {
    throw new Error(
      `Invalid preview range [${range.startIndex}, ${range.endIndex}] — session has ${allMessages.length} messages`,
    );
  }

  const targetMessages = allMessages.slice(range.startIndex, range.endIndex + 1);

  // 2. Generate the summary text without making DB changes.
  const summarizeFn = summarizer ?? defaultSquashSummarizer;
  const previewSummary = await summarizeFn(targetMessages, config);

  // 3. Calculate estimated token savings.
  const estimatedTokensSaved = estimateTokens(targetMessages);

  return {
    range,
    messageCount: targetMessages.length,
    estimatedTokensSaved,
    previewSummary,
    messages: targetMessages,
  };
}

// ---------------------------------------------------------------------------
// squashRollback — undo a squash operation
// ---------------------------------------------------------------------------

/**
 * Rollback a previous squash operation, restoring the original messages
 * and removing the summary message.
 *
 * @param db        Database handle
 * @param sessionId Target session
 * @param archiveId The squash archive entry ID to roll back
 * @returns The rollback result
 */
export async function squashRollback(
  db: DB,
  sessionId: string,
  archiveId: string,
): Promise<SquashRollbackResult> {
  // 1. Fetch the archive entry.
  const [archive] = await db.db
    .select()
    .from(squashArchives)
    .where(eq(squashArchives.id, archiveId))
    .limit(1);

  if (!archive) {
    throw new Error(`Squash archive not found: ${archiveId}`);
  }

  if ((archive.rollbackApplied as unknown as boolean) === true) {
    throw new Error(`Squash ${archiveId} has already been rolled back`);
  }

  // All remaining writes wrapped in a transaction so a mid-operation
  // failure does not leave the session in an inconsistent state.
  const result = await db.db.transaction(async (tx) => {
    // 2. Restore original messages.
    const originalMessages = archive.originalMessages as unknown as Array<{
      id: string;
      sessionId: string;
      role: string;
      content: unknown;
      createdAt: string;
    }>;

    let restoredCount = 0;
    for (const msg of originalMessages) {
      await tx
        .insert(messages)
        .values({
          id: msg.id,
          sessionId: msg.sessionId,
          role: msg.role,
          content: msg.content as Record<string, unknown>,
          tokenCount: 0,
          createdAt: new Date(msg.createdAt),
        })
        .onConflictDoNothing();
      restoredCount++;
    }

    // 3. Remove the summary message.
    const summaryMessageId = archive.summaryMessageId;
    if (summaryMessageId) {
      await tx.delete(messages).where(eq(messages.id, summaryMessageId));
    }

    // 4. Mark the archive as rolled back.
    const now = new Date();
    await tx
      .update(squashArchives)
      .set({
        rollbackApplied: true as unknown as Record<string, unknown>,
        rollbackTimestamp: now,
      })
      .where(eq(squashArchives.id, archiveId));

    // 5. Touch the session timestamp.
    await tx
      .update(sessions)
      .set({ updatedAt: now })
      .where(eq(sessions.id, sessionId));

    return { restoredCount, summaryMessageId };
  });

  return {
    restoredCount: result.restoredCount,
    summaryMessageId: result.summaryMessageId as string | null,
    applied: true,
  };
}

// ---------------------------------------------------------------------------
// getSquashLog — list all squash operations for a session
// ---------------------------------------------------------------------------

/**
 * Retrieve the ordered log of all squash operations for a session.
 *
 * @param db        Database handle
 * @param sessionId Target session
 * @returns Array of archive entries, newest first
 */
export async function getSquashLog(
  db: DB,
  sessionId: string,
): Promise<SquashArchiveEntry[]> {
  const rows = await db.db
    .select()
    .from(squashArchives)
    .where(eq(squashArchives.sessionId, sessionId))
    .orderBy(asc(squashArchives.createdAt));

  return rows.map(rowToArchiveEntry);
}

// ---------------------------------------------------------------------------
// getSquashStats — aggregated squash statistics
// ---------------------------------------------------------------------------

/**
 * Compute aggregated squash statistics for a session.
 *
 * @param db        Database handle
 * @param sessionId Target session
 * @returns Aggregated statistics
 */
export async function getSquashStats(
  db: DB,
  sessionId: string,
): Promise<SquashStats> {
  const rows = await db.db
    .select()
    .from(squashArchives)
    .where(eq(squashArchives.sessionId, sessionId))
    .orderBy(asc(squashArchives.createdAt));

  const totalSquashes = rows.length;
  if (totalSquashes === 0) {
    return {
      totalSquashes: 0,
      totalMessagesSquashed: 0,
      totalTokensSaved: 0,
      rollbacksPerformed: 0,
      lastSquashTimestamp: null,
      averageMessagesPerSquash: 0,
    };
  }

  let totalMessagesSquashed = 0;
  let totalTokensSaved = 0;
  let rollbacksPerformed = 0;
  let lastSquashTimestamp: Date | null = null;

  for (const row of rows) {
    totalMessagesSquashed += row.messageCount;
    totalTokensSaved += row.estimatedTokensSaved ?? 0;
    if ((row.rollbackApplied as unknown as boolean) === true) {
      rollbacksPerformed++;
    }
    // rows are ordered ascending, so the last one is the newest
    lastSquashTimestamp = row.createdAt;
  }

  return {
    totalSquashes,
    totalMessagesSquashed,
    totalTokensSaved,
    rollbacksPerformed,
    lastSquashTimestamp,
    averageMessagesPerSquash: Math.round((totalMessagesSquashed / totalSquashes) * 100) / 100,
  };
}

// ---------------------------------------------------------------------------
// Internal helpers
// ---------------------------------------------------------------------------

/**
 * Estimate the number of tokens in a list of messages.
 * Rough heuristic: ~4 characters per token.
 */
function estimateTokens(msgs: MessageData[]): number {
  let totalChars = 0;
  for (const m of msgs) {
    const content = typeof m.content === "string"
      ? m.content
      : JSON.stringify(m.content ?? "");
    totalChars += content.length;
  }
  return Math.ceil(totalChars / 4);
}

/**
 * Convert a raw DB row to a SquashArchiveEntry.
 */
function rowToArchiveEntry(row: Record<string, unknown>): SquashArchiveEntry {
  return {
    id: row.id as string,
    sessionId: row.sessionId as string,
    summaryMessageId: row.summaryMessageId as string | null,
    summary: row.summary as string,
    messageCount: row.messageCount as number,
    messageIds: row.messageIds as string[],
    estimatedTokensSaved: (row.estimatedTokensSaved ?? 0) as number,
    hotFiles: (row.hotFiles as string[]) ?? [],
    rollbackApplied: (row.rollbackApplied as unknown as boolean) === true,
    rollbackTimestamp: row.rollbackTimestamp as Date | null,
    createdAt: row.createdAt as Date,
  };
}

/**
 * Execute a squash: delete original messages, insert summary, write archive.
 *
 * Shared by squashRecent and squashInteractive.
 */
async function executeSquash(
  db: DB,
  sessionId: string,
  squashedMessages: MessageData[],
  summaryText: string,
  config: SquashConfig,
): Promise<{
  archive: SquashArchiveEntry;
  updatedSession: SessionData;
}> {
  // All DB writes wrapped in a transaction so a mid-operation failure
  // does not leave the session in an inconsistent state.
  const result = await db.db.transaction(async (tx) => {
    // 1. Delete the squashed messages.
    for (const msg of squashedMessages) {
      await tx.delete(messages).where(eq(messages.id, msg.id));
    }

    // 2. Insert the summary message.
    const now = new Date();
    const [summaryRow] = await tx
      .insert(messages)
      .values({
        id: crypto.randomUUID(),
        sessionId,
        role: "system",
        content: summaryText as unknown as Record<string, unknown>,
        tokenCount: 0,
        createdAt: now,
      })
      .returning();

    // 3. Calculate estimated token savings.
    const estimatedTokensSaved = estimateTokens(squashedMessages);

    // 4. Write archive entry.
    const messageIds = squashedMessages.map((m) => m.id);
    const originalMessages = squashedMessages.map((m) => ({
      id: m.id,
      sessionId: m.sessionId,
      role: m.role,
      content: m.content,
      createdAt: m.createdAt.toISOString(),
    }));

    const [archiveRow] = await tx
      .insert(squashArchives)
      .values({
        id: crypto.randomUUID(),
        sessionId,
        summaryMessageId: summaryRow.id,
        summary: summaryText,
        originalMessages: originalMessages as unknown as Record<string, unknown>,
        messageIds: messageIds as unknown as Record<string, unknown>,
        messageCount: squashedMessages.length,
        estimatedTokensSaved,
        hotFiles: (config.hotFiles ?? []) as unknown as Record<string, unknown>,
        rollbackApplied: false as unknown as Record<string, unknown>,
        createdAt: now,
      })
      .returning();

    // 5. Update session metadata to include squash log summary.
    const [existingSession] = await tx
      .select()
      .from(sessions)
      .where(eq(sessions.id, sessionId))
      .limit(1);

    const existingMetadata = (existingSession?.metadata as Record<string, unknown>) ?? {};
    const squashLog = (existingMetadata._squashLog as Array<{
      archiveId: string;
      timestamp: number;
      summary: string;
      messageCount: number;
    }>) ?? [];

    squashLog.push({
      archiveId: archiveRow.id,
      timestamp: now.getTime(),
      summary: summaryText,
      messageCount: squashedMessages.length,
    });

    await tx
      .update(sessions)
      .set({
        metadata: { ...existingMetadata, _squashLog: squashLog } as Record<string, unknown>,
        updatedAt: now,
      })
      .where(eq(sessions.id, sessionId));

    return {
      archiveRow,
      existingSession,
      existingMetadata,
      squashLog,
      now,
    };
  });

  return {
    archive: rowToArchiveEntry(result.archiveRow as unknown as Record<string, unknown>),
    updatedSession: {
      id: sessionId,
      title: result.existingSession?.title ?? "Session",
      parentId: result.existingSession?.parentId,
      branchPoint: result.existingSession?.branchPoint,
      metadata: { ...result.existingMetadata, _squashLog: result.squashLog },
      createdAt: result.existingSession?.createdAt ?? result.now,
      updatedAt: result.now,
    } as SessionData,
  };
}

// ---------------------------------------------------------------------------
// collectRecentPairs — internal helper
// ---------------------------------------------------------------------------

/**
 * Walk backwards through messages and identify the start/end indices of the
 * most recent `count` interaction pairs. Returns an array of [start, end]
 * tuples marking where each pair begins and ends.
 */
function collectRecentPairs(allMessages: MessageData[], count: number): Array<[number, number]> {
  const pairs: Array<[number, number]> = [];
  let i = allMessages.length - 1;

  while (i >= 0 && pairs.length < count) {
    if (allMessages[i]?.role === "assistant") {
      const assistantEnd = i;
      while (i >= 0 && allMessages[i]?.role !== "user") {
        i--;
      }
      if (i >= 0 && allMessages[i]?.role === "user") {
        pairs.push([i, assistantEnd]);
      }
      i = assistantEnd - 1;
    } else {
      i--;
    }
  }

  pairs.reverse();
  return pairs;
}

// ---------------------------------------------------------------------------
// defaultSquashSummarizer — local fallback
// ---------------------------------------------------------------------------

/**
 * Local fallback summarizer: produces a compact digest of the squashed
 * messages without calling the LLM. Suitable for testing and offline use.
 */
const defaultSquashSummarizer: SquashSummarizer = async (msgs) => {
  const lines: string[] = ["[Squashed summary of recent interactions]"];
  for (const m of msgs) {
    const content = typeof m.content === "string" ? m.content : JSON.stringify(m.content);
    const preview = content.slice(0, 200);
    lines.push(`- ${m.role}: ${preview}${content.length > 200 ? "…" : ""}`);
  }
  return lines.join("\n");
};